### ISSUE TITLE
'App.GeoFeature' object has no attribute 'Proxy'

### ISSUE THREAD

**Issue by glebaksenov12** [joelgraff/freecad.trails#93]
Got this error when creating a surface from a point cloud

```
14:49:34  Running the Python command 'Create Pad' failed:
Traceback (most recent call last):
  File "/home/gleb/.FreeCAD/Mod/freecad.trails/freecad/trails/geomatics/pad/create_pad.py", line 68, in Activated
    polyline = FreeCADGui.Selection.getSelection()[-2]

list index out of rangeRunning the Python command 'Create Surface' failed:
Traceback (most recent call last):
  File "/home/gleb/.FreeCAD/Mod/freecad.trails/freecad/trails/geomatics/surface/create_surface.py", line 73, in Activated
    if obj.Proxy.Type == 'Trails::PointGroup':

'App.GeoFeature' object has no attribute 'Proxy'Running the Python command 'Create Surface' failed:
Traceback (most recent call last):
  File "/home/gleb/.FreeCAD/Mod/freecad.trails/freecad/trails/geomatics/surface/create_surface.py", line 73, in Activated
    if obj.Proxy.Type == 'Trails::PointGroup':

'App.GeoFeature' object has no attribute 'Proxy'
```

**Comment by HakanSeven12** [comment]
Can you send the file?

**Comment by glebaksenov12** [comment]
[calle.zip](https://github.com/joelgraff/freecad.trails/files/7643081/calle.zip)

**Comment by glebaksenov12** [comment]
I'm using freecad 0.19.2 conda from official releases page on github and trails (alpha) cloned from repository.

**Comment by glebaksenov12** [comment]
> Can you send the file?

I sent the file in the previous message. Can you say me which version of freecad is most recommended for using trails WB? Maybe something is wrong with my installation (FreeCAD_0.19-24291-Linux-Conda_glibc2.12-x86_64.AppImage from official github page running on Pop_OS 21.04 with kde plasma. Trails WB cloned from repository)

**Comment by HakanSeven12** [comment]
FreeCAD 19.2 is good. But trails version is old. There is a new repo: https://github.com/HakanSeven12/Trails

I will take a look at file tomorrow

**Comment by glebaksenov12** [comment]
I updated trails and got a similar error

```
17:31:30  Running the Python command 'Create Terrain' failed:
Traceback (most recent call last):
  File "/home/gleb/.FreeCAD/Mod/Trails-main/Trails/guitools/gui_terrain.py", line 75, in Activated
    if obj.Proxy.Type == 'Trails::Cluster':

'App.GeoFeature' object has no attribute 'Proxy'
```

**Comment by HakanSeven12** [comment]
The problem is you created a point cloud but you need to use "Import Point File" tool in Trails wb.

**Comment by glebaksenov12** [comment]
I finally did it. I had a couple of issues with the import tool, but it turned out to be an xyz file problem. Then I had some complications to find the generated points, but I located them with the shortcut (V, F). Thank you very much for helping me and for all your work doing this WB.
